### ISSUE TITLE
curl command doesn't work

### ISSUE THREAD

**Issue by piforce** [Evidlo/remarkable_printer#10]
When I try the curl command on my remarkable2  I get the error:  -sh: curl: command not found

**Comment by Evidlo** [comment]
Should be fixed now.

**Comment by piforce** [comment]
get an error wget: bad address 'raw.githubusercontent.com'

I installed true the install.sh file now.

**Comment by Evidlo** [comment]
Is the remarkable connected to WiFi?

**Comment by piforce** [comment]
yes it is connected with wifi.

**Comment by Evidlo** [comment]
That's the error I get when the tablet doesn't have internet access.

**Comment by piforce** [comment]
i think i found the problem. Think that my raspberry with pihole was the problem after restarting the raspberry it worked.
