### ISSUE TITLE
New release with updated ExecStart path

### ISSUE THREAD

**Issue by axelson** [Evidlo/remarkable_printer#14]
Currently if you follow the instructions in the README you will end up with a non-working printer service since `install.sh` is from master but the downloaded release.zip has the version of `printer.service` from before this commit: https://github.com/Evidlo/remarkable_printer/commit/df870008fe5b763754f1456c1590f2ed37522827

Publishing a new release (and updated release.zip) will fix this issue.

BTW, thanks for creating this, it's very handy!

**Comment by Evidlo** [comment]
Thanks, I just made a new release.

**Comment by axelson** [comment]
Great, thanks!
