### ISSUE TITLE
[Feature Request] Split pages in two

### ISSUE THREAD

**Issue by LeifAndersen** [Evidlo/remarkable_printer#15]
I have fairly low vision and often find reading one printed page on the remarkable is quite difficult. As such, I cut each page in half before sending it to the remarkable. I would also like to be able to do this using your printer script.

It seems to me that there are two possible ways to do this:

1. Somehow add in the .pdd file a new page size that is half the current 'remarkable' size, and let the remarkable scale the page up on its own.

2. Create a new printer device that:
    1. Prints to a pdf.
    2. Cuts the page in half
    3. Sends this new pdf to be printed by your existing printer.

Option #1 seems better (and easier) to me, but I don't really know enough about CUPS (or whatever the printing subsystem for linux is) to do it myself (at least not yet).

**Comment by Evidlo** [comment]
I created a [pdfsplit](https://github.com/Evidlo/remarkable_printer/tree/pdfsplit) branch with a CUPS filter that splits the page.  It requires mutool to be installed.

    make install_config_split

I think something like this make more sense as a [xochitl mod](https://github.com/ddvk/remarkable-hacks/) though.
