### ISSUE TITLE
Feature: Rename sent document to website title

### ISSUE THREAD

**Issue by dansbandit** [Evidlo/remarkable_printer#21]
My workflow is as follows:

I see an interesting article, send it to the remarkable with this tool.
It has the name of 'Printed' and I rename it to something else. 

Is there anyway to change the name of the sent PDF to for example the website title? Is it even possible to send information via the printer?

**Comment by Evidlo** [comment]
Can you try running `sudo make install_config` with the latest commit?  There was a problem with the printer configuration file so the title information wasn't being sent.

**Comment by axelson** [comment]
Since I'm in the same boat is `sudo make install_config` all that's required to update?

**Comment by Evidlo** [comment]
Should be.

Though, I made some minor changes to the service itself that you should
probably get.

**Comment by dansbandit** [comment]
It works!

Thanks a lot!

**Comment by philippmuench** [comment]
The title on macOS is still "Printed" if someone knows what I need to change please let me know
