### ISSUE TITLE
Mac OS problems with `make install_config` (printer driver)

### ISSUE THREAD

**Issue by philippmuench** [Evidlo/remarkable_printer#22]
Thanks for providing this code! I used it without errors but after reinstallation of OS Big Sur the `make install_config` script is causing an error (screenshot: https://imgur.com/a/q0Pww2Q) I tried to manually set up the printer but its outputting `%!PS-Adobe-3.0` and not `%!PDF-1.5`. Maybe you have an idea what I need to adapt or if I need additional drivers? Thanks!

**Comment by Evidlo** [comment]
Does it still happen after `sudo make install_config` on your new installation?

When manually adding the printer, is there a PDF option under the "Use:" dropdown?

**Comment by philippmuench** [comment]
I have the same error when using `sudo make install_config` and I also have reset my printer config. 

I tried the two different setting under "Use". I also tried to manually use the `remarkable.ppd` there, too. 

Screenshots are here https://imgur.com/a/AmmpNP5

**Comment by Evidlo** [comment]
I don't have an OSX machine to test on, so I can't be much help with this issue.

If you figure it out, let me know and I can update the instructions accordingly.

Choosing `remarkable.ppd` really should be sending a PDF though.  Here is the unmodified PDF ppd (zipped) from my machine:

[pdf_generic.zip](https://github.com/Evidlo/remarkable_printer/files/6145651/pdf_generic.zip)

**Comment by Evidlo** [comment]
You might also try configuring the printer directly through CUPS web interface: https://github.com/Evidlo/remarkable_printer/pull/18/files

**Comment by philippmuench** [comment]
Thanks! Just found out that cups web interface gives me a more detailed error:

```
Idle - "File “/usr/libexec/cups/filter/pdftopdf” not available: No such file or directory"
```

And I had `cgpdftopdf` in  `/usr/libexec/cups/filter/` but no `pdftopdf `

This issue is therefore fixed via

```
sudo ln -s /usr/libexec/cups/filter/cgpdftopdf /usr/libexec/cups/filter/pdftopdf
```

Thanks for your help! : )
