### ISSUE TITLE
Printer works best for me with custom paper size on windows

### ISSUE THREAD

**Issue by dreadful-brain** [Evidlo/remarkable_printer#28]
Maybe this could be an addition to docs:
I use remarkable_printer on win10 with a custom paper-size of 15,70cm x 20,96cm (the default papersize for pdf-exports from rM2). With that format I have a good readable text size and do not have to adjust the pdf view in rM2, because toolbar fits perfect in the default left margin.

Therefore I had to:
1. define a custom paper size "reMarkable" in print server-settings
2. Enable custom paper sizes for the PrintToPdf-based reMarkable-Printer (a guide for that can be found in https://franklinheath.co.uk/2015/08/29/custom-page-sizes-for-microsoft-print-to-pdf/)

Now I can just select this format as a print layout e.g. in Outlook, OneNote or Browser and i have a very good readable print in my reMarkable.

**Comment by Evidlo** [comment]
Could you give a screenshot?  The default print settings work pretty well for me already.

https://text.npr.org/984274079

![Capture](https://user-images.githubusercontent.com/5455841/114250700-29ae4c00-9964-11eb-8cd2-f894b9ca60ac.PNG)
![IMG_2021_04_09_18_12_59](https://user-images.githubusercontent.com/5455841/114250707-2f0b9680-9964-11eb-83f4-d5e9f1e342ad.jpg)
