### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sokion** [Evidlo/remarkable_printer#3]
Sorry if the title's misleading. Last a few lines didn't seem to go well. Any advice to spare?

```
Darwin:remarkable_printer-master me$ make install
env GOOS=linux GOARCH=arm GOARM=5 go build -o printer.arm
ssh-add
Enter passphrase for /Users/me/.ssh/id_rsa: 
Identity added: /Users/me/.ssh/id_rsa (me@email.com)
ssh root@10.11.99.1 systemctl stop printer
scp printer.arm root@10.11.99.1:
printer.arm                                             100% 3238KB   6.4MB/s   00:00    
scp printer.service root@10.11.99.1:/etc/systemd/system
printer.service                                         100%  154    79.5KB/s   00:00    
ssh root@10.11.99.1 <<- ENDSSH
Pseudo-terminal will not be allocated because stdin is not a terminal.
systemctl daemon-reload
make: systemctl: No such file or directory
make: *** [install] Error 1
```

**Comment by Evidlo** [comment]
Can you manually ssh into the reMarkable and execute 

    systemctl daemon-reload
    systemctl enable printer.service
    systemctl start printer.service

**Comment by sokion** [comment]
Yes I executed it and managed to adding it to the printer (I'm on mac OS). But the printed pages don't show up in reMarkable.

**Comment by Evidlo** [comment]
If you could start the service in debug mode, that would help to figure out what's going on.

Add `-debug` after the `-restart` option in the printer.service file, then run `make install` again.

You can view the debug log with `journalctl -f --unit printer` in the reMarkable's console.

**Comment by Evidlo** [comment]
You might try the easy install instructions.  It seems they should work on OSX now.
