### ISSUE TITLE
need to reboot remarkable to see printed. 

### ISSUE THREAD

**Issue by piforce** [Evidlo/remarkable_printer#30]
I have version 2.7.0.51 with ddvk hacks and with toltec installed koreader and remux
When printing to the remarkable the file doesn't show up in the list. When I restart the device the file printed appears.

**Comment by Evidlo** [comment]
The service is supposed to restart the device automatically after the upload is complete.

Can you show your logs?

**Comment by piforce** [comment]
I have to look how to do logs. It works now because I did by accident a system update to 2.7.153 but now remux/toltec wont work. So it is something with that.

**Comment by Evidlo** [comment]
https://github.com/Evidlo/remarkable_printer#debugging

**Comment by piforce** [comment]
Now I have the problem again. Installed, remux, koreader, ddvk hacks on version 2.8.0.98. I have to restart the device to see the printed documents. It doesn't make difference if i print with cups or directly with the pdf printer. 
When I had only koreader en ddvk hacks it just worked. Before I had koreader installed with the dirtyhack of ddvk and not by toltec.

log
reMarkable: ~/ journalctl --unit printer -f
-- Logs begin at Wed 2021-08-11 10:31:51 CEST. --
Aug 11 10:31:54 reMarkable systemd[1]: Started Native printing to reMarkable.
Aug 11 10:31:54 reMarkable printer.arm[186]: Debugging enabled
Aug 11 10:31:54 reMarkable printer.arm[186]: Listening on 0.0.0.0:9100
Aug 11 10:35:54 reMarkable printer.arm[186]: Saving PDF to: /home/root/.local/share/remarkable/xochitl/822451d1-a983-4b63-8744-5d3ed6498075.pdf
Aug 11 10:35:55 reMarkable printer.arm[186]: %PDF-1.7
Aug 11 10:35:55 reMarkable printer.arm[186]: PDF begin
Aug 11 10:35:55 reMarkable printer.arm[186]: Saving metadata to /home/root/.local/share/remarkable/xochitl/822451d1-a983-4b63-8744-5d3ed6498075.metadata
Aug 11 10:35:55 reMarkable printer.arm[186]: Saving content file to /home/root/.local/share/remarkable/xochitl/822451d1-a983-4b63-8744-5d3ed6498075.content

**Comment by piforce** [comment]
When I disable remux it the printerfunction works again. When remux enabled it goes wrong.

**Comment by Evidlo** [comment]
There is supposed to be some [debug lines](https://github.com/Evidlo/remarkable_printer/blob/master/main.go#L84-L94) in the log about restarting xochitl.

Since those aren't getting printed, maybe check `/etc/systemd/system/printer.service` and make sure the `-restart` option is present.  It should be there already, though.

**Comment by piforce** [comment]
Restart is present. 
The strange thing is when I disable remux it works see log. At9:06 is with remux disabled.  The printer job from 9:08 is with remux enabled.

```
reMarkable: ~/ journalctl --unit printer -f
-- Logs begin at Thu 2021-08-12 09:05:07 CEST. --
Aug 12 09:06:03 reMarkable printer.arm[187]: @PJL SET MANUALDUPLEX=OFF
Aug 12 09:06:03 reMarkable printer.arm[187]: @PJL SET MANUALFEED=OFF
Aug 12 09:06:03 reMarkable printer.arm[187]: @PJL SET OVERRIDEA4WITHLETTER=YES
Aug 12 09:06:03 reMarkable printer.arm[187]: @PJL SET RET=NOTSET
Aug 12 09:06:03 reMarkable printer.arm[187]: @PJL ENTER LANGUAGE = PDF
Aug 12 09:06:03 reMarkable printer.arm[187]: %PDF-1.7
Aug 12 09:06:03 reMarkable printer.arm[187]: PDF begin
Aug 12 09:06:03 reMarkable printer.arm[187]: Saving metadata to /home/root/.loca                        l/share/remarkable/xochitl/0343d665-29c5-464e-a523-4597a6577d10.metadata
Aug 12 09:06:03 reMarkable printer.arm[187]: Saving content file to /home/root/.                        local/share/remarkable/xochitl/0343d665-29c5-464e-a523-4597a6577d10.content
Aug 12 09:06:03 reMarkable printer.arm[187]: Restarting xochitl

Aug 12 09:08:12 reMarkable printer.arm[187]: Saving PDF to: /home/root/.local/sh                        are/remarkable/xochitl/8204382a-ef48-41c2-9bc5-a813bdfa9b33.pdf
Aug 12 09:08:12 reMarkable printer.arm[187]: [13B blob data]
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL JOB NAME = "remarkable_printer                        " DISPLAY = "311 WOONKAMERNUC\thuis pc woonka"
Aug 12 09:08:12 reMarkable printer.arm[187]: Setting title to: remarkable_printe                        r
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET USERNAME = "WOONKAMERNUC\t                        huis pc woonkamer"
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET DUPLEX=OFF
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET PAPER=A4
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET RESOLUTION=600
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET BORDERLESS=ON
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET EDGETOEDGE=YES
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET JOBOFFSET=ON
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET LOWSUPPLIES=CONTINUE
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET MANUALDUPLEX=OFF
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET MANUALFEED=OFF
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET OVERRIDEA4WITHLETTER=YES
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL SET RET=NOTSET
Aug 12 09:08:12 reMarkable printer.arm[187]: @PJL ENTER LANGUAGE = PDF
Aug 12 09:08:12 reMarkable printer.arm[187]: %PDF-1.7
Aug 12 09:08:12 reMarkable printer.arm[187]: PDF begin
Aug 12 09:08:12 reMarkable printer.arm[187]: Saving metadata to /home/root/.loca                        l/share/remarkable/xochitl/8204382a-ef48-41c2-9bc5-a813bdfa9b33.metadata
Aug 12 09:08:12 reMarkable printer.arm[187]: Saving content file to /home/root/.                        local/share/remarkable/xochitl/8204382a-ef48-41c2-9bc5-a813bdfa9b33.content
```

**Comment by nylki** [comment]
Same issue here, also using launcher `remux` on the device.

**Comment by Evidlo** [comment]
https://github.com/Evidlo/remarkable_printer/issues/19
