### ISSUE TITLE
How to affect print resolution, ie to get a print to fill the whole page?

### ISSUE THREAD

**Issue by cspoons** [Evidlo/remarkable_printer#32]
I'm having an issue where whatever I print only fills up about 1/4th of remarkable page. Is there a way to tell whatever I print to stretch to fill the whole screen, or otherwise automatically get stretched to 1404x1872?

**Comment by Evidlo** [comment]
There's no settings in remarkable_printer like that because it just takes the PDF generated by your OS.

Maybe your printer settings are set to print 4 pages per side?
