### ISSUE TITLE
Automatic installation not working after release 9

### ISSUE THREAD

**Issue by dreadful-brain** [Evidlo/remarkable_printer#33]
install.sh tries to download /releases/latest/download/release.zip, but release 9 does not contain a release.zip.
So installation is currently only possible by either building it, or manually downloading the older release.

**Comment by DutchJoe** [comment]
Experiencing the same problem. Unzipping previous versions result in the error message "unzip: short read".

Don't know what's happening.

**Comment by Evidlo** [comment]
Should be fixed now.
