### ISSUE TITLE
Allow different service name for restart

### ISSUE THREAD

**Issue by dorianim** [Evidlo/remarkable_printer#35]
Hi,

First, thank you for this project, It's very helpful!
I'd like to request one small feature: It would be nice to make the name of the restarted service configurable in order for this to work with different launchers. I am using the [remux launcher](https://rmkit.dev/apps/remux), and therefore I have to restart the service `remux` instead of `xochitl`.

Best Regards
Dorian

**Comment by zelomel** [comment]
Hi @Evidlo 

Same problem here. I have to kill xochitl manually to update the file list and get my printed document. Before using remux, the restart was done automatically. 

Z.

**Comment by Evidlo** [comment]
See https://github.com/toltec-dev/toltec/issues/515#issuecomment-996187717 and https://github.com/Evidlo/remarkable_printer/issues/19
