### ISSUE TITLE
On OSX - how to change PS to PDF ?

### ISSUE THREAD

**Issue by dirkx** [Evidlo/remarkable_printer#36]
Following the instruction:

<img width="794" alt="Screenshot 2022-05-18 at 11 43 49" src="https://user-images.githubusercontent.com/392583/169010316-64817d98-21ae-4408-aac7-cfa8f2f297fd.png">

one ends up with a Generic printer that sends PDF and as a result; an error

      May 18 09:39:34 reMarkable printer.arm[2470]: Couldn't find PDF start

on the side of the Remarkable. How does one force on OSX the sending of a pure PDF ?

**Comment by dirkx** [comment]
Answering my own question - I think the issue is in this line:

          sudo cp rmfilter /usr/lib/cups/filter

of the Makefile. This should probably be

        test -d /usr/lib/cups/filter && sudo cp rmfilter /usr/lib/cups/filter

to only install it there if that dir exists so that the next line is always executed.

**Comment by Evidlo** [comment]
Should be fixed with 11.0.0
