### ISSUE TITLE
Adding the reMarkable as a printer for windows

### ISSUE THREAD

**Issue by zelomel** [Evidlo/remarkable_printer#4]
I added my reMarkable as printer in win10.
I followed your instructions to install and start the printer service on the reMarkable using a VM with ubuntu.

To add the printer in windows, I followed this instructions:
1. Select “Start” and type “printers” in the search box.
2. Choose “Printers & scanners“.
3. Select "Add a printer or a scanner"
4. Wait few seconds and click on "The printer I that I want isn’t listed" option
5. Select “Add a printer using a TCP/IP address or hostname” , then select “Next“.
6. Select “TCP/IP Device” in the “Device type” list.
7. Enter the IP address of the printer (10.11.99.1). Select “Next“.
8. Wait few seconds to allow windows to find your printer
9. Select "Hewlett Packard Jet Direct"
10. Select "Microsoft" and the "Microsoft Print to PDF"
11. Rename the printer, "reMarkable" for example

Works fine

**Comment by charlienormand** [comment]
This is cool where do you find the HP Jet Direct driver, because I don’t see it in the windows10 default list under HP.

Also, on the remarkable, where do the sent prints end up residing?

Thanks

**Comment by Evidlo** [comment]
@charlienormand 

The files end up in the main Documents view.

**Comment by Evidlo** [comment]
This is linked in the README now.
