### ISSUE TITLE
Printed File Has No Data

### ISSUE THREAD

**Issue by fatalkarma100** [Evidlo/remarkable_printer#40]
I had this installed and working great.  Updated to rM sw 3.0 which updated the IP address.  I deleted the original install and reinstalled the native printer hack, chose existing driver, and then went back to chnage driver to MS Print to PDF.  Now I am getting only one page no matter how many pages (tried in Excel and Word) and with no data - blank one page.  Checked the MS Print to PDF printer and it printed a test page with printer data.

Appreciate thoughts on how to fix this.

**Comment by oricgn** [comment]
Me too. I have the same problem.

**Comment by djerius** [comment]
Commit 621cbee515ddfdbb84102910e3dcdd72d21246a2 fixed this for me.

**Comment by Evidlo** [comment]
Yep, try with the latest version and report back.  If it still doesn't work try the `Debugging` section of the README and paste the log here.

**Comment by fatalkarma100** [comment]
Updated with latest version, still printing only one blank page, log below:

reMarkable: ~/ journalctl --unit printer -f
-- Logs begin at Sat 2023-01-14 06:55:07 UTC. --
Jan 21 07:28:01 reMarkable systemd[1]: printer.service: Failed with result 'exit-code'.
Jan 21 07:28:01 reMarkable systemd[1]: printer.service: Scheduled restart job, restart counter is at 2.
Jan 21 07:28:01 reMarkable systemd[1]: Stopped Native printing to reMarkable.
Jan 21 07:28:01 reMarkable systemd[1]: Started Native printing to reMarkable.
Jan 21 07:28:01 reMarkable printer.arm[254]: Listening on 0.0.0.0:9100
Jan 21 07:33:03 reMarkable printer.arm[254]: Saving PDF to /home/root/.local/share/remarkable/xochitl/9796700c-80c6-4acc-b0f9-aeb46db68be1.pdf
Jan 21 07:33:03 reMarkable printer.arm[254]: [%PDF-1.7
Jan 21 07:33:03 reMarkable printer.arm[254]: ]
Jan 21 07:33:03 reMarkable printer.arm[254]: [PDF begin]
Jan 21 07:33:03 reMarkable printer.arm[254]: Saving metadata to /home/root/.local/share/remarkable/xochitl/9796700c-80c6-4acc-b0f9-aeb46db68be1.metadata
Jan 21 07:38:00 reMarkable printer.arm[254]: Saving PDF to /home/root/.local/share/remarkable/xochitl/a07cc4ef-6028-47ed-84af-a4eaecba406a.pdf
Jan 21 07:38:00 reMarkable printer.arm[254]: [%PDF-1.7
Jan 21 07:38:00 reMarkable printer.arm[254]: ]
Jan 21 07:38:00 reMarkable printer.arm[254]: [PDF begin]
Jan 21 07:38:00 reMarkable printer.arm[254]: Saving metadata to /home/root/.local/share/remarkable/xochitl/a07cc4ef-6028-47ed-84af-a4eaecba406a.metadata

**Comment by fatalkarma100** [comment]
> Yep, try with the latest version and report back. If it still doesn't work try the `Debugging` section of the README and paste the log here.

Updated with latest version, still printing only one blank page, please see log below:

reMarkable: ~/ journalctl --unit printer -f
-- Logs begin at Sat 2023-01-14 06:55:07 UTC. --
Jan 21 07:28:01 reMarkable systemd[1]: printer.service: Failed with result 'exit-code'.
Jan 21 07:28:01 reMarkable systemd[1]: printer.service: Scheduled restart job, restart counter is at 2.
Jan 21 07:28:01 reMarkable systemd[1]: Stopped Native printing to reMarkable.
Jan 21 07:28:01 reMarkable systemd[1]: Started Native printing to reMarkable.
Jan 21 07:28:01 reMarkable printer.arm[254]: Listening on 0.0.0.0:9100
Jan 21 07:33:03 reMarkable printer.arm[254]: Saving PDF to /home/root/.local/share/remarkable/xochitl/9796700c-80c6-4acc-b0f9-aeb46db68be1.pdf
Jan 21 07:33:03 reMarkable printer.arm[254]: [%PDF-1.7
Jan 21 07:33:03 reMarkable printer.arm[254]: ]
Jan 21 07:33:03 reMarkable printer.arm[254]: [PDF begin]
Jan 21 07:33:03 reMarkable printer.arm[254]: Saving metadata to /home/root/.local/share/remarkable/xochitl/9796700c-80c6-4acc-b0f9-aeb46db68be1.metadata
Jan 21 07:38:00 reMarkable printer.arm[254]: Saving PDF to /home/root/.local/share/remarkable/xochitl/a07cc4ef-6028-47ed-84af-a4eaecba406a.pdf
Jan 21 07:38:00 reMarkable printer.arm[254]: [%PDF-1.7
Jan 21 07:38:00 reMarkable printer.arm[254]: ]
Jan 21 07:38:00 reMarkable printer.arm[254]: [PDF begin]
Jan 21 07:38:00 reMarkable printer.arm[254]: Saving metadata to /home/root/.local/share/remarkable/xochitl/a07cc4ef-6028-47ed-84af-a4eaecba406a.metadata

**Comment by djerius** [comment]
Does the metadata file have the fields lastOpened and LastOpenedPage?

**Comment by djerius** [comment]
> Commit [621cbee](https://github.com/Evidlo/remarkable_printer/commit/621cbee515ddfdbb84102910e3dcdd72d21246a2) fixed this for me.

I actually compiled from source; I didn't use the release.

**Comment by fatalkarma100** [comment]
> Does the metadata file have the fields lastOpened and LastOpenedPage?

I can't find the folder .local.  It's not under /home/root.  
![image_2023-01-21_120047455](https://user-images.githubusercontent.com/85419878/213884970-30eab243-fd7c-42f0-84ee-5ca1c68efc47.png)

**Comment by djerius** [comment]
It's a "hidden" directory. Your file browser application should have a configuration parameter which controls their visibility.

Alternatively,  

`cat /home/root/.local/share/remarkable/xochitl/a07cc4ef-6028-47ed-84af-a4eaecba406a.metadata`

when you're logged into the tablet via `ssh`

**Comment by fatalkarma100** [comment]
![image_2023-01-24_164953245](https://user-images.githubusercontent.com/85419878/214454939-923eabc7-9172-4f62-a024-2f906aff7440.png)
> Does the metadata file have the fields lastOpened and LastOpenedPage?

Here's the log:
{
    "deleted": false,
    "lastModified": "1674288795464",
    "lastOpened": "1674286383000",
    "lastOpenedPage": 0,
    "metadatamodified": true,
    "modified": true,
    "parent": "trash",
    "pinned": false,
    "synced": false,
    "type": "DocumentType",
    "version": 0,
    "visibleName": "Printed"
}

**Comment by fatalkarma100** [comment]
> It's a "hidden" directory. Your file browser application should have a configuration parameter which controls their visibility.
> 
> Alternatively,
> 
> `cat /home/root/.local/share/remarkable/xochitl/a07cc4ef-6028-47ed-84af-a4eaecba406a.metadata`
> 
> when you're logged into the tablet via `ssh`

Any help would be appreciated.  lastOpenedpage:0  - does this mean nothing was opened for print?

**Comment by Evidlo** [comment]
Can you compare that file to one of the `.metadata` files of a document that displays correctly?  Each document has other files besides `.metadata`, so you might look for differences there, too.

I'm not running the latest xochitl version so I can't check this myself.

**Comment by djerius** [comment]
I've attached a zip file of what is stored on my rm2 when printing to the tablet via this driver.  I can view it properly on the rm2.

You can try a couple of things: 

1. scp the zip file to your rm2, unzip it, and make sure that you can view the resultant PDF. I presume you'll have to reboot or whatever magic is required to get the rm2 to scan the directory.
2. print the PDF to the rm2 and compare the resulting files on the rm2 to the ones in the zip file.


[5a9b51b3-e859-424e-b630-2e9abfbd88d8.zip.txt](https://github.com/Evidlo/remarkable_printer/files/10726360/5a9b51b3-e859-424e-b630-2e9abfbd88d8.zip.txt)

**Comment by bsvh** [comment]
I ran into this issue as well. The problem seems to be that the `.content` file is being detected as invalid and is overwritten with the fileType set to notebook instead of pdf. If I ssh in and edit the content file manually to change the fileType back to pdf, the file can then be opened as a pdf.

I guess the `CONTENT_TEMPLATE` needs to be changed.

**Comment by Evidlo** [comment]
@bsvh Can you paste an example of a good `.content` file here?  What's invalid in `CONTENT_TEMPLATE`?

**Comment by bsvh** [comment]
Looking at the source,  `CONTENT_TEMPLATE` only sets the `fileType`, and I'm guessing the new firmware decided that's not enough? In any case, here's the `.content` of a test document I uploaded using the official app

```
{
    "coverPageNumber": 0,
    "customZoomCenterX": 0,
    "customZoomCenterY": 936,
    "customZoomOrientation": "portrait",
    "customZoomPageHeight": 1872,
    "customZoomPageWidth": 1404,
    "customZoomScale": 1,
    "documentMetadata": {
        "title": "My Test Document"
    },
    "extraMetadata": {
    },
    "fileType": "pdf",
    "fontName": "",
    "formatVersion": 1,
    "lineHeight": -1,
    "margins": 125,
    "orientation": "portrait",
    "originalPageCount": 1,
    "pageCount": 1,
    "pageTags": [
    ],
    "pages": [
        "6c797d30-ee46-46fa-9adf-e6fad66e722b"
    ],
    "redirectionPageMap": [
        0
    ],
    "sizeInBytes": "81034",
    "tags": [
    ],
    "textAlignment": "justify",
    "textScale": 1,
    "zoomMode": "bestFit"
}
```

And here's what it looks like after using the printer driver

```
{
    "coverPageNumber": -1,
    "customZoomCenterX": 0,
    "customZoomCenterY": 936,
    "customZoomOrientation": "portrait",
    "customZoomPageHeight": 1872,
    "customZoomPageWidth": 1404,
    "customZoomScale": 1,
    "documentMetadata": {
    },
    "extraMetadata": {
    },
    "fileType": "notebook",
    "fontName": "",
    "formatVersion": 1,
    "lineHeight": -1,
    "margins": 125,
    "orientation": "portrait",
    "originalPageCount": -1,
    "pageCount": 1,
    "pageTags": [
    ],
    "pages": [
        "5d1af207-b572-4b97-9b0f-d1ba294f64b7"
    ],
    "redirectionPageMap": [
    ],
    "sizeInBytes": "0",
    "tags": [
    ],
    "textAlignment": "justify",
    "textScale": 1,
    "zoomMode": "bestFit"
}
```

If I change the filetype to pdf and restart xochitl, I can then open it.

**Comment by djerius** [comment]
I'm puzzled by this, as I'm having zero problems (even w/ the latest bump to 3.2).  The .contents files have a proper filetype of PDF when I print them to the tablet.

I did recompile the executable rather than use the one on the releases page. Maybe that's the difference...

AHA.  The dates of the files in the [release.zip](https://github.com/Evidlo/remarkable_printer/releases/download/v11.0.1/release.zip) for 11.0.1 file are older than the relevant commit on Jan 5, 2023:

```
$ unzip -l /tmp/release.zip 
Archive:  /tmp/release.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  3388094  2022-12-11 21:36   printer.arm
  3749171  2022-12-11 21:36   printer.x86
      165  2020-12-29 01:08   printer.service
---------                     -------
  7137430                     3 files
```

I think an older version is in the released zip file.

**Comment by Evidlo** [comment]
I must've forgotten to `make clean` before making the last release.  @djerius Could you try with `11.0.2`?

**Comment by djerius** [comment]
@Evidlo It works!

For the record:

```
/tmp $ unzip -l release.zip 
Archive:  release.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  2992129  2023-03-10 19:51   printer.arm
  3057960  2023-03-10 19:51   printer.x86
      165  2020-12-29 01:08   printer.service
---------                     -------
  6050254                     3 files
/tmp $ unzip release.zip 
Archive:  release.zip
  inflating: printer.arm             
  inflating: printer.x86             
  inflating: printer.service         
/tmp $ sha256sum printer.arm
77ef9c2ae7d0ad3fdd4a1982f9ae5cb46744d6486bcc526a359ef75d78a4e645  printer.arm
```

On the tablet:

```
root@reMarkable:~/bin# sha256sum /home/root/bin/printer.arm
77ef9c2ae7d0ad3fdd4a1982f9ae5cb46744d6486bcc526a359ef75d78a4e645  /home/root/bin/printer.arm
```

**Comment by Evidlo** [comment]
Thanks for the help everyone!  I'll reopen if there are more issues.
