### ISSUE TITLE
How can i uninstall the Code on my Remarkable 2

### ISSUE THREAD

**Issue by MawaCiN** [Evidlo/remarkable_printer#41]
Hi this Script is not working on my Remarkable. How can i uninstall this script complete from my Device ?

**Comment by jordanmalecki** [comment]
Based off the `install.sh` script I did the following to uninstall:
```
systemctl disable --now printer.service
rm /etc/systemd/system/printer.service
rm /home/root/bin/printer.arm
systemctl daemon-reload
```
I could have missed something so correct me if I am wrong.

**Comment by Evidlo** [comment]
That looks correct to me.
