### ISSUE TITLE
on make install, error: "Failed to stop printer.service: Unit printer.service not loaded."

### ISSUE THREAD

**Issue by elliottw** [Evidlo/remarkable_printer#8]
MacOS: 11.0.1
remarkable 2 currently up to date (as of Dec 8, 2020)

**Comment by elliottw** [comment]
Apple -> System Preferences -> Printers and Scanners -> right click in "printers" header at the top of printer list and "Reset Printing System"
then make install
then make install_config host=10.11.99.1
has remarkable showing up in Printers and Scanners

When trying to print, remarkable stalls and printing queue never gets completed. Queue item states "Printing - The printer is not responding"

**Comment by Evidlo** [comment]
Is the reMarkable accessible?  Can you ping the address?  

If you ssh into the device and run

    journalctl --unit printer -f

then submit a print job, what do you see?

**Comment by elliottw** [comment]
root@reMarkable:~# journalctl --unit printer -f
-- Logs begin at Mon 2020-12-14 16:28:04 UTC. --

looks like no response

**Comment by coozoo** [comment]
I'm on linux. Actually in this issue I can see two.

- first one it's that script simply trying to stop service which doesn't exists yet (it whats described in title)

- 2nd one it prints nice 1-2 page documents at least from libreoffice 

but when I've tried to print djvu book (about 100 pages) it really stuck it loads one core for 100% with gs process  and I wasn't able to wait till the end

So i've tried to pint just a 5 pages and and it took more than minute.

So maybe it's the same case? if huge book it simply takes long time and RM goes to sleep?

**Comment by Evidlo** [comment]
@elliottw I simplified the install process, so you shouldn't have this problem anymore.  Check the readme.

**Comment by elliottw** [comment]
tried to pull updates and `make install`, same result.
as for the curl process, same as https://github.com/Evidlo/remarkable_printer/issues/10

**Comment by Evidlo** [comment]
@elliottw Fixed

**Comment by elliottw** [comment]
awesome!

**Comment by elliottw** [comment]
thanks a bunch
