### ISSUE TITLE
Print to pdf driver removed from recent version of Windows 10 

### ISSUE THREAD

**Issue by nchmel** [Evidlo/remarkable_printer#9]
I found a weird problem and even weirder workaround for printing from Windows 10. 

In the newest version of Windows 10 the "Microsoft Print to PDF" driver seem to have been removed from the drivers list (but it's still in the system somewhere) as long as you have the default Print to PDF printer that comes with Windows 10. You can enable it from "Turn Windows Features on or off"

 So to add the printer to Windows 10 I had to add two steps to the old procedure:

Select “Start” and type “printers” in the search box.
Choose “Printers & scanners“.
Select "Add a printer or a scanner"
Wait few seconds and click on "The printer I that I want isn’t listed" option
Select “Add a printer using a TCP/IP address or hostname” , then select “Next“.
Select “TCP/IP Device” in the “Device type” list.
Enter the IP address of the printer (10.11.99.1 for USB connection or IP of you wifi connection). Select “Next“.
Wait few seconds to allow windows to find your printer
Select "Hewlett Packard Jet Direct"
Select "Microsoft" and the "Microsoft Print to PDF" 
**If the "Microsoft Print to PDF" driver is not on the list, choose any other driver (doesn't matter which one). 
Rename the printer, "reMarkable" for example
**If you chose another driver above, go to the Printers & Scanners/Manage/Printer Properties/Advanced
In the Driver: drop down menu choose "Microsoft Print of PDF" which is now visible, click OK

**Comment by Evidlo** [comment]
Thanks.  I've copied this to https://github.com/Evidlo/remarkable_printer/wiki/Windows-Setup
